version: '3.7'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always
  zookeeper:
    image: zookeeper:3.4.9
    ports:
      - "2181:2181"
    volumes:
      - ./kafka/zookeeper/data:/data
      - ./kafka-data/zookeeper/datalog:/datalog
  kafka:
    image: confluentinc/cp-kafka:5.4.1
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    volumes:
      - ./kafka-data/kafka/data:/var/lib/kafka/data
    depends_on:
      - zookeeper
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
volumes:
  kafka-data: ~/kafka
